# ===========================================================
# DATABASE CONNECTION (PostgreSQL local)
# ===========================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/cabinet_avocat
spring.datasource.username=postgres
spring.datasource.password=simone

spring.datasource.hikari.maximum-pool-size=5

# ===========================================================
# JPA / HIBERNATE
# ===========================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ===========================================================
# SERVER CONFIGURATION
# ===========================================================
server.port=8080

# ===========================================================
# JWT
# ===========================================================
security.jwt.secret=8mX4rT9pL2zQ7wK1nV6yB3cD5fH8jS0aP4uR7eT1yU9iO2p
security.jwt.expiration-ms=86400000