# ================= DATABASE =================
spring.datasource.url=jdbc:postgresql://dpg-d6sn3jfgi27c73d7pom0-a.oregon-postgres.render.com:5432/cabinet_avocat_gkg5
spring.datasource.username=cabinet_avocat_gkg5_user
spring.datasource.password=zieH6dmNsewyHGZvFjNkNviSqpfXMM8g
spring.datasource.hikari.maximum-pool-size=5

# ================= JPA =================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ================= SERVER =================
server.port=${PORT:8080}

# ================= JWT =================
security.jwt.secret=8mX4rT9pL2zQ7wK1nV6yB3cD5fH8jS0aP4uR7eT1yU9iO2p
security.jwt.expiration-ms=86400000

spring.mail.host=mail.privateemail.com
spring.mail.port=587
spring.mail.username=contact@cabinet-tsapy.com
spring.mail.password=Contact#CabinetTsapy2026
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

file.upload-dir=uploads/documents
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB