# ===========================================================
# DATABASE CONNECTION (Render PostgreSQL)
# ===========================================================
spring.datasource.url=jdbc:postgresql://dpg-d4ma1mbuibrs738f3lp0-a:5432/cabinet_avocat
spring.datasource.username=cabinet_avocat_user
spring.datasource.password=1m1hA1uDzvRrw0XUNB6twCC8AEzRZU1C

spring.datasource.hikari.maximum-pool-size=5

# ===========================================================
# JPA / HIBERNATE
# ===========================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ===========================================================
# SERVER CONFIGURATION
# ===========================================================
server.port=8080

# ===========================================================
# JWT
# ===========================================================
security.jwt.secret=8mX4rT9pL2zQ7wK1nV6yB3cD5fH8jS0aP4uR7eT1yU9iO2p
security.jwt.expiration-ms=86400000